name: "Print Message"
description: "Print message"
secrets:
  TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: Print message
      shell: bash
      run: |
        echo ${{ secrets.TOKEN }}   
