name: Token

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  pass-data:
    runs-on: "ubuntu-latest"
    steps:
      - uses: matthewtamayo/sample-action@main
        with:
            token: ${{ secrets.TOKEN }}

